### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by akshay1027** [mogilogan/IEEE-CIC#1]
- sponsor spelling mistake
- add margin on top of sponsors section
- 
![image](https://user-images.githubusercontent.com/65683151/223508175-4c25b760-841a-4243-abc0-8126c2be5d46.png)
- Spacing should be the same for the top and bottom of a section. Showing one example below where the margin-bottom is more than the top. 
- 
![image](https://user-images.githubusercontent.com/65683151/223508656-4864e93f-3c33-4423-aa97-92b5ab02e8ea.png)

**Comment by mogilogan** [comment]
Corrected spelling, added margin and spacing is checked.
